### ISSUE TITLE
Discordancia entre el inicio y las plantas de temporada.

### ISSUE THREAD

**Issue by Anghelorus** [AlvaroGlezDaw/Jardineria-DAW-grupo-1#11]
Alvaro habia subido un css y un html adaptando lo que yo pase, pero david ha subido un html principal y un css diferente, no se si lo habias hablado en clase o algo pero si no  habria que aclararse  en que html y que css usar, para que cada uno no cree una cosa diferente, tambien habria que juntar las flores de temporada y que el menu de inicio llevase a esa pagina.

**Comment by Davidfr4** [comment]
Yo es que tenía que hacer la página de inicio. El que más guste estéticamente, es solo copiar el código del contenido para adaptarlo, si queréis lo puedo pasar con la misma estructura, es para tener unos colores más limpios, y diseño más elegante.

**Comment by AlvaroGlezDaw** [comment]
Si lo habiamos hablado que en principio( antes de subirlo todo) cada uno haria un css para su html con unos estandares comunes, como fue el usar flexbox, pero luego hay que ir juntandolo todo, colores y demas propiedades en un solo css, que de hecho habria que abrir una issue( perfectamente esta podria servir) y que alguien se encarge de ella, yo mismo la me la puedo asignar, ya sea para relacionar el menu con las paginas html asi como ir juntando los css.
