### ISSUE TITLE
Falta la galeria de fotos de la pagina

### ISSUE THREAD

**Issue by AlvaroGlezDaw** [AlvaroGlezDaw/Jardineria-DAW-grupo-1#7]

**Comment by AlvaroGlezDaw** [comment]
@Davidfr4, ¿si ponemos la galeria de fotos en el menu de inicio rollo presentacion breve? ¿como lo ves?

**Comment by Davidfr4** [comment]
Vale, si quieres puedo mirar de hacer en el inicio, una presentación breve de la web, que es para jardinería... y debajo la galería, quito la del menú de la izquierda y pongo una mejor @AlvaroGlezDaw

**Comment by AlvaroGlezDaw** [comment]
Si esta perfecto eso, genial

**Comment by Davidfr4** [comment]
Estoy trabajando en ello, entre hoy y mañana ya estará subido, que me está dando algo de problemas las medidas
